[package]
name = "observer_examples"
version = "0.1.0"
edition = "2024"

[dependencies]
high_gain_observer = { path = "../high_gain_observer" }
control_system = { path = "../control_system" }
hifitime = "4.2.5"
ndarray = "0.16.1"
plotly = "0.14"
rand = "0.10.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"